name: CelestialDungeons
version: '${project.version}'
main: me.km127pl.celestialdungeons.CelestialDungeons
api-version: 1.19
authors: [ km127pl ]
description: CelestialDungeons is a plugin that generates unique and challenging dungeons for players to explore. With its rogue-like elements, you never know what dangers or treasures await around each corner. Embark on an epic adventure through the stars and discover the secrets hidden within the dungeon.
